# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

#remote DB - 219.150.142.129 --HNCATV
# development:
  # adapter: mysql2
  # encoding: utf8
  # host: hooludb.dyndns.biz
  # port: 3306
  # reconnect: false
  # database: development
  # username: hoolusoft
  # password: h00lus0ft
  # socket: /var/run/mysqld/mysqld.sock

#remote DB - hoolu.dyndns.biz
# development:
  # adapter: mysql2
  # encoding: utf8
  # host: hoolu.dyndns.biz
  # port: 3306
  # reconnect: false
  # database: development
  # username: hoolusoft
  # password: hoolusoft
  # socket: /var/run/mysqld/mysqld.sock

#local DB
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: development
  pool: 5
  username: root
  password: honker198874
  socket: /var/run/mysqld/mysqld.sock

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

# production:
  # adapter: mysql2
  # encoding: utf8
  # reconnect: false
  # database: development_production
  # pool: 5
  # username: root
  # password:
  # socket: /var/run/mysqld/mysqld.sock
